services:
  backend:
    build: ./spotbeat-backend
    container_name: spotbeat-backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    build: ./spotbeat
    container_name: spotbeat-frontend
    ports:
      - "5174:80" # frontend served via nginx
    depends_on:
      - backend
    env_file:
      - ./.env

  db:
    image: postgres:15
    container_name: spotbeat-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spotbeat
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
